### ISSUE TITLE
Project update - Week #10

### ISSUE THREAD

**Issue by mkd38** [mkd38/quranic-stylometrics#10]
Team members report back on the past week's progress, including cosmetic changes made to site design, results of Voyant analysis, and development of XSLT reading view.

Team discusses and concludes that Voyant analysis is interesting but not particularly compelling or illuminating. Team concludes that these results should not feature heavily in our analysis, though they may be useful as additional color. 

Team began to brainstorm and sketch the graphical elements will be used to support our analysis. To answer the research questions we asked at the outset of the project, we propose to use SVG to create: 

1.  A pie chart for each text reflecting device use as a portion of the whole, which can show us in relative terms whether some texts use particular devices more than others; 

2. A  three-bar histogram with devices along the x-axis and raw count on the y-axis  to compare each text's use of a device in absolute terms; 

We also discussed possibly creating a density plot, but upon further reflection this may be duplicative of our histogram. 

**Tasks for next meeting:**

- [ ] Replace empty ayah elements in the Arabic markup with wrapped elements so that XSLT developed by Austin can be used to create reading view - MK 
- [ ] Create site feature that will highlight active tab for better UX - Austin  
- [ ] Continue to develop CSS and XHTML in consultation with team - Aisha 

**Design notes:**

- [ ] Add 'text box' to for better contrast between font color and background 
- [ ] Add images of translators to 'About' page 
- [ ] Image captions
