### ISSUE TITLE
Project Update - Week #6

### ISSUE THREAD

**Issue by mkd38** [mkd38/quranic-stylometrics#6]
## Attendance 

All team members present. 

## Update on Midterm Tasks (Due 1 March 2023): 

- [ ] Tidy repository (**Austin**)
- [ ] Push final draft copies of Surahs 1, 13, and 17 to folder analyzedsuwarXML in the repo. Ensure that title contains translator name and surname of the team member who annotated this text as well as surah number (**ALL**)
- [ ] Revise and validate Arabic schema against all three surahs (**MK**)
- [ ] Update README.md with a summary of research questions (**MK**)
- [ ] Revise and validate English schema against all three surahs (**Aisha & Austin**) 

## Minutes 

Each team member supplies a brief update on progress made since last week. Then, the bulk of the meeting is devoted to discussion of standardizing markup across the three texts. 

### **Questions addressed:** 

Re: Tagging the ninety-nine names of God. 

- Throughout the text, God is referred to by many names (ex. ar-Rahman, ar-Rahim, al-Malik). These names have hitherto been marked as element `<praise>` taking attribute `@amplification`. Members discuss and conclude that these names should be tagged simply as `<amplification>`. 
- The names of God often occur together, thus leading to the question of whether these names should be tagged together as a single element, ex. `<amplification>الرحمن الرحيم</amplification> بسم الله` (MK's preferred approach approach) or as separate elements, ex.  `In the name of God <amplification>the Most Gracious</amplification> <amplification>the Most Merciful</amplification>` (Aisha's preferred approach). Members discuss and decide to take Aisha's proposal. 

## Tasks for Next Meeting (3/19): 
- [ ] Complete When2Meet provided by Renee and to meet virtually to conduct a direct comparison of the three iterations of each surah for final edits, after which markup will be frozen (**ALL**). 
- [ ] Begin drafting wireframe for project site (**ALL**). 
- [ ] Research multi-lingual topic modeling with MALLET and report back on feasibility of incorporating this tool into our analysis (**MK**).
